install ack
install apple-gcc42
install csshx
install direnv
install ffmpeg
install git
install htop-osx
install imagemagick
install libxslt
install libyaml
install maven
install mplayer
install mtr
install nmap
install pcre
install redis
install ssh-copy-id
install tmux
install tree
install watch
install wget
install zsh-completions
